# Определение массива строк
PACKAGE := book.chapter5.
BINPATH := bin
COMPILE := javac -encoding utf8 -d $(BINPATH)
RUN := java -classpath $(BINPATH) $(PACKAGE)


# Exercise 1
Class1:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 2
Class2:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 3, 4
Class3:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 5, 6
Dog:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 7
Class4:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 8
Class5:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 9
Class6:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 10, 11, 12
Class7:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 13, 14
Class8:
	$(COMPILE) $@.java ..\chapter2\Print.java
	$(RUN)$@

# Exercise 15, 16, 17, 18
MyString:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 19, 20
Class9:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 21, 22
Money:
	$(COMPILE) $@.java
	$(RUN)$@

clean:
	rm -rf $(BINPATH)