# Определение массива строк
PACKAGE := book.chapter5.
BINPATH := bin
COMPILE := javac -encoding utf8 -d $(BINPATH)
RUN := java -classpath $(BINPATH) $(PACKAGE)


# Exercise 1
Class1:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 2
Class2:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 3, 4
Class3:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 5, 6
Dog:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 7
Class4:
	$(COMPILE) $@.java
	$(RUN)$@

clean:
	rm -rf $(BINPATH)