# Определение массива строк
PACKAGE := book.chapter7.
BINPATH := bin
COMPILE := javac -encoding utf8 -d $(BINPATH)
RUN := java -classpath $(BINPATH) $(PACKAGE)


# Exercise 3
Class3:
	$(COMPILE) $@.java
	$(RUN)$@

clean:
	rm -rf $(BINPATH)