# Определение массива строк
BINPATH := bin
COMPILE := javac -encoding utf8 -d $(BINPATH)


# Exercise 1 from 6 chapter
Class1:
	$(COMPILE) chapter6TestClass1.java .\exercises\src\main\java\book\chapter6\Class1.java
	java -classpath $(BINPATH) chapter6TestClass1

clean:
	rm -rf $(BINPATH)