# spring.application.name=timesheet
# spring.datasource.url=jdbc:h2:mem:test
# spring.datasource.username=sa
# spring.datasource.password=

server:
  port: 3333
spring:
  security:
    client:
#      registration:
#        keycloak:
#          client-id: unsafe_client
      provider:
        keycloak:
          authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth
          token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
  application:
    name: timesheet-page
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true