# Определение массива строк
PACKAGE := book.chapter3.
BINPATH := bin
COMPILE := javac -encoding utf8 -d $(BINPATH)
RUN := java -classpath $(BINPATH) $(PACKAGE)


# Exercise 1
TestPrint:
	$(COMPILE) $@.java ..\chapter2\Print.java
	$(RUN)$@

# Exercise 2, 3
CombineFloat:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 4
Speed:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 5, 6
Dog:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 7
Coin:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 8
LongBin:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 9
ExpMinMax:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 10
Operators:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 11, 12, 13
Shift:
	$(COMPILE) $@.java
	$(RUN)$@

# Exercise 14
StringEquals:
	$(COMPILE) $@.java
	$(RUN)$@

clean:
	rm -rf $(BINPATH)